### ISSUE TITLE
Fixed IP with CUNX?

### ISSUE THREAD

**Issue by cgawron** [tostmann/culfw#2]
The readme.md mentions commands to set a fixed IP address for the CUNX. 
Is this really supported? It doesn't work for me.

I'm experiencing network stability issues with DHCP enabled - the CUNX gets unreachable after some time. I'm not sure whether this is really related to DHCP, but I would like to set a fixed IP to try if the connection gets more stable.

**Comment by tostmann** [comment]
Wid - DHCP enabled flag (Wid01 - DHCP an // Wid00 DHCP aus)

Wid00 vergessen?
