### ISSUE TITLE
CUNX.hex ist kein hex-file...

### ISSUE THREAD

**Issue by 404frank** [tostmann/culfw#3]
Hi Tostmann,

wenn ich die CUNX.hex öffne sieht das eher aus wie Quellcode und nicht wie ein hex-File. Wo liegt hier der Fehler?

Gruß Frank

**Comment by tostmann** [comment]
Das kann ich nicht nachvollziehen

**Comment by 404frank** [comment]
Ok, ich jetzt auch nicht mehr. Die aktuelle CUNX.hex konnte ich nicht in Flip laden - Invalid HEX file syntax.

Beim öffnen einer alten CUNX.hex habe ich in Notepad dann Hex-Code gesehen:
:10000000A8C50000CBC50000C9C50000C7C50000D9
:10001000C5C50000C3C50000C1C50000BFC50000C4
:10002000BDC50000BBC50000B9C50000B7C50000D4

Die neue wurde, wie ich jetzt wohl verstehe, als html angezeigt:
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
....
Ab Zeile 450 dann wohl der Hex Code:
 <div itemprop="text" class="blob-wrapper data type-text">
      <table class="highlight tab-size js-file-line-container" data-tab-size="8">
      <tr>
        <td id="L1" class="blob-num js-line-number" data-line-number="1"></td>
        <td id="LC1" class="blob-code blob-code-inner js-file-line">:10000000A8C50000CBC50000C9C50000C7C50000D9
</td>
      </tr>
      <tr>
        <td id="L2" class="blob-num js-line-number" data-line-number="2"></td>

Frage ist, wie ich die aktuelle CUNX.hex sauber als hex-File downloaden kann?

File, save as ging nicht...

Danke und Gruß,
Frank

**Comment by cgawron** [comment]
Hallo Frank,
Du musst auf den Button "RAW" klicken, wenn Du die Datei über das Web-GUI runterladen möchtest.

Beste Grüße
Christian

**Comment by 404frank** [comment]
Alles klar, gefunden. Vielen Dank.
